services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - APP_ENV=dev
      - FONTAWESOME_NPM_AUTH_TOKEN=${FONTAWESOME_NPM_AUTH_TOKEN}

  messenger-async:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: messenger-async
    environment:
      - APP_ENV=dev
    depends_on:
      - app

  scheduler-ffta-licensees:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: scheduler-ffta_licensees
    environment:
      - APP_ENV=dev
    depends_on:
      - app

###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${MARIADB_VERSION:-10.11.5}
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-ChangeMe}
      MARIADB_USER: ${MARIADB_USER:-symfony}
    volumes:
      - db-data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

  adminer:
    image: dehy/adminer
    ports:
      - "8081:80"

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###